services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345677
      MYSQL_DATABASE: watchito
    volumes:
      - mysql_data:/var/lib/mysql



volumes:
  mysql_data: